version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
 
    environment:
        - SERVER_PORT=${SERVER_PORT}
        - CONNECTIONSTRING=${CONNECTIONSTRING}

    
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"