version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
 
    environment:
        - SERVER_PORT=8080
        - CONNECTIONSTRING=mongodb+srv://mbanda:mbanda@biashara-point.zco8t.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"